name: OwnBlocksMySQL
main: me.cvenomz.OwnBlocks.OwnBlocks
version: 0.2
author: cvenomz
commands:
  ownblocks:
    aliases: [ob]
    description: toggle per-player OwnBlocks activation
    usage: /<command>
