name: OwnBlocksX
main: me.cvenomz.OwnBlocks.OwnBlocks
version: 0.2.1
author: cvenomz
commands:
  ownblocksx:
    aliases: [obx]
    description: toggle per-player OwnBlocksX activation
    usage: /<command>
